language: python
python:
  - "3.5"
before_install:
  - ls -la
  - cd ociedoo
install:
  - pip install -r requirements.txt
  - pip install --editable .
  - pip install pytest
# command to run tests
script:
  - pytest
branches:
  only:
    - dev
notifications:
  email:
    recipients:
      - remy@coopiteasy.be
    on_success: change
    on_failure: change
